version: '2.0'

services:
  shiny:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ['3838:3838']
    volumes:
      - '.:/srv/shiny-server'
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
